# Generated by Django 3.1.7 on 2021-09-17 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cos_like',
        ),
    ]
